### ISSUE TITLE
Cannot build project

### ISSUE THREAD

**Issue by conky2** [groue/WWDCCompanion#1]
Hi, I'm getting the following error when trying to build.  Thanks for your help!
![screen shot 2017-01-24 at 10 57 59 am](https://cloud.githubusercontent.com/assets/25021281/22254991/0630de42-e224-11e6-995f-6189e338ffc0.png)

**Comment by groue** [comment]
Hello @conky2

Did you follow the [installation instruction](https://github.com/groue/WWDCCompanion#how-to-run-the-app)? What happened then?

**Comment by conky2** [comment]
Yes, I followed the installation instruction.  This was the result that I
got.  It seems to be Xcode having a problem with the FTS5 command vs. FTS3.

**Comment by groue** [comment]
Yes. Actually I can reproduce the problem from a fresh clone... Looks like the git repo is missing something. Let me check that.

**Comment by groue** [comment]
@conky2, Until I find out for good what's wrong, here is how you can have the app compile:

1. Build (and fail, as in your screenshot)
2. Quit Xcode
3. Delete ~/Library/Developer/Xcode/DerivedData/
4. Delete WWDCCompanion.xcodeproj/xcuserdata/
5. Delete WWDCCompanion.xcworkspace/xcuserdata/
6. Open WWDCCompanion.xcworkspace and run WWDCCompanion app, which should now compile and run.

Tell me if this works.

The trouble is in the integration of GRDB with a custom build of SQLite (an advanced GRDB usage that this app is supposed to demonstrate - hum). Most apps don't need a custom build.

**Comment by groue** [comment]
Precisely speaking, the FTS3/4 full text engines are available in the SQLite version that ships with iOS. This makes them much easier to integrate in your app (see [installation](https://github.com/groue/GRDB.swift#installation))

The FTS5 engine is more advanced, but it requires a custom SQLite build, and the setup is still delicate, as you can see.

So everything depends on your full-text needs. Check out https://github.com/groue/GRDB.swift#full-text-search for more information.

**Comment by conky2** [comment]
Got it.  Thanks for the thorough help.  I very much appreciate it.

**Comment by groue** [comment]
Good luck in your search for the full-text tool you need, @conky2! If you keep on exploring GRDB, and have any other question or trouble, please open an issue at http://github.com/groue/GRDB.swift/issues.

**Comment by conky2** [comment]
The instructions as provided worked.  Thanks so much for your help.  GRDB
is really neat.  I'm going to spend a lot more time looking at it.  It
provides a ton of what I'm looking for.  Thanks again.

**Comment by groue** [comment]
👍
